builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/ahmetozer/bosphorus/cmd.BuildVersion={{.Version}}
    flags:
      - -trimpath
    goos:
      - linux
      - freebsd
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
archives:
  - format: binary
    name_template: '{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    files:
      - none*
release:
  draft: true
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"